<?php

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('courses')->delete();

		App\Course::create(array ('idcourses' => 1, 'title' => 'Consultoria Presencial e Marketing', 'category' => 'Mercado e vendas', 'description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum', 'price' => 150, 'start' => '2017-06-21 10:00:00', 'finish' => '2017-06-22 16:00:00', 'consultants_idconsultants' => 1, 'addresses_idaddresses' => 1, 'created_at' => '2017-06-21 10:00:00', 'updated_at' => '2017-06-21 16:00:00'));

		App\Course::create(array ('idcourses' => 2, 'title' => 'Aprendendo a aprender: ferramentas mentais poderosas para ajudá-lo a dominar assuntos difíceis ', 'category' => 'Mercado e vendas', 'description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum', 'price' => 12.8, 'start' => '2017-06-21 10:00:00', 'finish' => '2017-07-21 18:00:00', 'consultants_idconsultants' => 2, 'addresses_idaddresses' => 2, 'created_at' => '2017-06-21 10:00:00', 'updated_at' => '2017-07-21 16:00:00'));

		App\Course::create(array ('idcourses' => 3, 'title' => 'Negociações de sucesso: estratégias e habilidades essenciais', 'category' => 'Mercado e vendas', 'description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum', 'price' => 222 , 'start' => '2017-06-21 07:00:00', 'finish' => '2017-08-12 16:00:00', 'consultants_idconsultants' => 3, 'addresses_idaddresses' => 3, 'created_at' => '2017-06-21 10:00:00', 'updated_at' => '2017-06-21 16:00:00'));

		App\Course::create(array ('idcourses' => 4, 'title' => 'Introdução à Ciência da Computação com Python ', 'category' => 'Mercado e vendas', 'description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum', 'price' => 234.09, 'start' => '2017-06-21 07:00:00', 'finish' => '2017-06-30 12:00:00', 'consultants_idconsultants' => 4, 'addresses_idaddresses' => 4, 'created_at' => '2017-06-21 10:00:00', 'updated_at' => '2017-06-21 16:00:00'));

		App\Course::create(array ('idcourses' => 5, 'title' => 'ABC da Gestão de Projetos.', 'category' => 'Mercado e vendas', 'description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum', 'price' => 345.99, 'start' => '2017-06-21 09:00:00', 'finish' => '2018-01-16 21:00:00', 'consultants_idconsultants' => 5, 'addresses_idaddresses' => 5, 'created_at' => '2017-06-21 10:00:00', 'updated_at' => '2017-06-21 16:00:00'));

		App\Course::create(array ('idcourses' => 6, 'title' => 'Criação de Startups: Como desenvolver negócios inovadores', 'category' => 'Mercado e vendas', 'description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum', 'price' => 150, 'start' => '2017-06-21 10:00:00', 'finish' => '2017-06-21 16:00:00', 'consultants_idconsultants' => 6, 'addresses_idaddresses' => 6, 'created_at' => '2017-06-21 10:00:00', 'updated_at' => '2017-06-21 16:00:00'));

		App\Course::create(array ('idcourses' => 7, 'title' => 'Crie e publique aplicativos para iPhone, iPad e Apple Watch', 'category' => 'Mercado e vendas', 'description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum', 'price' => 150, 'start' => '2017-06-21 10:00:00', 'finish' => '2017-07-12 16:00:00', 'consultants_idconsultants' => 7, 'addresses_idaddresses' => 7, 'created_at' => '2017-06-21 10:00:00', 'updated_at' => '2017-06-21 16:00:00'));

		App\Course::create(array ('idcourses' => 8, 'title' => 'As Ferramentas do Cientista de Dados', 'category' => 'Mercado e vendas', 'description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum', 'price' => 150, 'start' => '2017-06-21 10:00:00', 'finish' => '2017-06-21 16:00:00', 'consultants_idconsultants' => 8, 'addresses_idaddresses' => 8, 'created_at' => '2017-06-21 10:00:00', 'updated_at' => '2017-06-21 16:00:00'));

		App\Course::create(array ('idcourses' => 9, 'title' => 'As Ferramentas do Cientista de Dados', 'category' => 'Mercado e vendas', 'description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum', 'price' => 150, 'start' => '2017-06-21 10:00:00', 'finish' => '2017-06-21 16:00:00', 'consultants_idconsultants' => 9, 'addresses_idaddresses' => 9, 'created_at' => '2017-06-21 10:00:00', 'updated_at' => '2017-06-21 16:00:00'));

		App\Course::create(array ('idcourses' => 10, 'title' => 'Negociações de sucesso: estratégias e habilidades essenciais', 'category' => 'Mercado e vendas', 'description' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum', 'price' => 150, 'start' => '2017-06-21 10:00:00', 'finish' => '2017-06-21 16:00:00', 'consultants_idconsultants' => 10, 'addresses_idaddresses' =>  10, 'created_at' => '2017-06-21 10:00:00', 'updated_at' => '2017-06-21 16:00:00'));
    }
}
